### PR TITLE
Mappings Changes

### PR DESCRIPTION
**Pull request by jonafanho**
* Rename `RenderTrains` to `MainRenderer`
* Use `-server` builds for Minecraft Transit Railway (without the assets) for smaller library sizes
* Remove `shouldNotRender` (this has been removed from Minecraft Transit Railway)

### CODE REVIEW

**Comment by Kenny-Hui** [comment]
What are the ways to get MTR assets working in Minecraft Debug Mode now that it depends on the server build?

**Comment by jonafanho** [comment]
Oh I haven't thought about that, I think using a clientside resource pack (with all the assets) might be the best option. I thought using a JAR file without assets would make it much smaller (70 MB down to 11 MB), since always uploading large JAR files to GitHub doesn't seem like a good idea in the long run. For example, diffs are usually unable to be shown properly or it just takes a long time to load.

**Comment by Kenny-Hui** [comment]
Ideally dependency should be pulled from elsewhere instead of stored in the repo, but if there's no other way then I guess I'll have to use the client RP method

**Comment by jonafanho** [comment]
I agree, ideally we would do that, but I just don't have anything set up yet. Perhaps after I start uploading to Modrinth, we can use their API to easily import the mod as a dependency through Gradle.

**Review by Kenny-Hui — APPROVED** [review]

**Pull request merged**
